import Navbar from "@/components/Navbar";
import clsx from "clsx";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const className = "max-w-screen-2xl mx-auto w-full px-4 md:px-6 lg:px-10";

  return (
    <html lang="en">
      <body
        className={clsx(inter.className, "flex flex-col items-center mb-40")}
      >
        <Navbar className={clsx(className, "bg-red-100")} />
        <div className={className}>{children}</div>
      </body>
    </html>
  );
}
